name: hostel_management_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bilions_ui: ^1.0.19
  card_loading: ^0.3.0
  cloud_firestore: ^4.13.5
  double_back_to_close_app: ^2.1.0
  fancy_shimmer_image: ^2.0.3
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: forte
      fonts:
        - asset: assets/fonts/FORTE.TTF

    - family: aquatico
      fonts:
        - asset: assets/fonts/AQUATICO.OTF
  
    - family: inkfere
      fonts:
        - asset: assets/fonts/INKFREE.TTF
  
